sudo: required
language: php
php:
- 5.4
before_install :
- /home/travis/.phpenv/versions/5.5/bin/composer self-update
install:
script:
- phpunit
after_success:
- chmod 600 ./.ssh/dream.pem
- ssh -i ./.ssh/dream.pem dhc-user@67.205.61.31 -o "StrictHostKeyChecking no" exit
- ./deploy production
after_failure:
after_script: