sudo: required
language: php
php:
- 5.5
- 5.4
before_install :
- /home/travis/.phpenv/versions/5.5/bin/composer self-update
install:
before_script:
- chmod +x deploy.sh
script:
- phpunit
after_success:
- Deploy/deploy.sh
after_failure:
after_script: